### ISSUE TITLE
Unknown method getMedia

### ISSUE THREAD

**Issue by mlehel** [Catchoom/craftar-php#12]
Hi,

I am trying to call the getMedia method of a Management object, but I get an "PHP Fatal error:  Uncaught Error: Call to undefined method craftar\Management::getMedia()".

My code is:

include("craftar/Management.php");
	
use craftar\Management;
	
$apiKey = "xxxx";
	
$management = new Management(Management::API_VERSION_0, $apiKey);
	
$response = $management->getMedia('8f7d2a2b80324ed38dc8726c7c140bba');

What am I doing wrong?

**Comment by kpantic** [comment]
Hi Lehel, 

We just updated the library 4 days ago adding Media management and some other features. Check that the version of the Management.php file you have is in fact the latest version.

**Comment by mlehel** [comment]
Hi Kristoffer,

Thank you for the quick response, no problem, reverting to v1.1, which works like a charm!

I have another question though, I've just run into this problem: through the management API I did not manage to upload a video file of 110MB with createMedia, it throws a 413 error, while the web interface allows me to add such large media files. What am I doing wrong?

**Comment by mlehel** [comment]
And one more thing, if you have time for another question :) I managed to upload a smaller video, but it does not appear normally in the media library, I am sending and receiving the following (is there a way to create media with an URL instead of a local file?):

Sending:

$apiKey = "xxxxx";
$collectionId = "dfca38bae99b4e7b91d28380a0cc4f7c";

$management = new Management(Management::API_VERSION_0, $apiKey);
		
$newMediaPath = 'videos/motoGP.mp4';
	
$response = $management->createMedia($newMediaPath);
	
$newMedia = $response->getBody();
	
print '<pre>';
print_r($newMedia);
print '</pre>';

Receiving:

stdClass Object
(
    [created] => 2016-10-28T09:26:01.314695
    [file] => https://crs-beta-catchoom.s3.amazonaws.com/media/36cde22bb2994c798bc62c14f25b2718/motoGP.mp4
    [meta] => stdClass Object
        (
            [status] => OK
        )

    [mimetype] => video/mp4
    [name] => motoGP.mp4
    [resource_uri] => /api/v0/media/36cde22bb2994c798bc62c14f25b2718/
    [uuid] => 36cde22bb2994c798bc62c14f25b2718
)

**Comment by mlehel** [comment]
Besides the above I am having trouble adding a simple image into the scene. I've created a scene manually, thus I know, that the media URL and the UUID of the added image exists. This is how I try to add a new item into my collection, which puts an existing media item on top of the trigger image (but the image does not appear anywhere unfortunately):

include("craftar/Management.php");

use craftar\Management;

$apiKey = "xxxx";
$collectionId = "yyyy";

$management = new Management(Management::API_VERSION_0, $apiKey);

$json = (object)[
	'version' => 2,
	'contents_v2' => [
		(object)[
			'alpha' => 1,
			'type' => 'image',
			'image_url' => 'https://crs-beta-catchoom.s3.amazonaws.com/media/9d607538e2d04c4883e2e1a5c275b834/play.png',
			'media_uuid' => '9d607538e2d04c4883e2e1a5c275b834',
			'rotation_euler' => [0, 0, 0],
			'rotation_matrix' => [1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1],
			'scale' => [1, 1, 1],
			'translation' => [0, 0, 1]
		]
	]
];

$name = "Item uploaded from PHP";

$optionalData = array("trackable" => true, 'content' => $json);

$response = $management->createItem($collectionId, $name, $optionalData);

$item = $response->getBody();

$imagePath = "images/bot-city.jpg";

$response = $management->createImage($item->uuid, $imagePath);

**Comment by kpantic** [comment]
Hi @mlehel I've made some updates to the library which addresses the issues you brought up. To upload videos, use the new createVideoMedia method which receives a video URL. The createMedia method should only be used for Image Media and 3D Object Media.

As for the item contents issue, it had to with the Json decoding the library did to the object you were sending. I've fixed this in the latest update and you should be good now.

**Comment by mlehel** [comment]
Thank you so much! I will test the new version ASAP and get back to you!

**Comment by mlehel** [comment]
Works like a charm, thank you so much!
