### ISSUE TITLE
[Bug] Response error when trying to create an image using PHP 7.0

### ISSUE THREAD

**Issue by xserrat** [Catchoom/craftar-php#9]
Hi,

I found a bug when I call the method `Management::createImge` using PHP 7.0. This method return a response with an error because as we can see here https://github.com/Catchoom/craftar-php/commit/b0ec07e5f566bc8c979adca512d71634c4e0991d#diff-f1f461f79b61367eabfb0a29a6d986dbR105, the method `Management::file_create` called inside the `createImage` returns `@fileName` instead of `curl_file_create($filename)`. 

In order to solve this issue only need to parsing the PHP version as follow:

```php

protected function file_create($filename)
{
     if (PHP_VERSION >= 5.5)
     {
         return curl_file_create($filename);
     } 
     else 
     {
         return "@$filename";
     }
}

```

Thanks!!

**Comment by kpantic** [comment]
Hi @xserrat, thanks for bringing this bug to our attention, I just made a commit which will fix this issue: https://github.com/Catchoom/craftar-php/commit/d5747de22565b565fb0b106868cc67aaa223bbf9

**Comment by xserrat** [comment]
Thank you too @kpantic. That's better with `version_compare` function 👍
